# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MatrixModule_dialog_base.ui'
#
# Created: Wed Apr 15 16:13:36 2015
# by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_MatrixElaboratorDialogBase(object):
    def setupUi(self, MatrixElaboratorDialogBase):
        MatrixElaboratorDialogBase.setObjectName(_fromUtf8("MatrixElaboratorDialogBase"))
        MatrixElaboratorDialogBase.resize(670, 371)
        self.button_box = QtGui.QDialogButtonBox(MatrixElaboratorDialogBase)
        self.button_box.setGeometry(QtCore.QRect(480, 330, 171, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel | QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.groupBox_7 = QtGui.QGroupBox(MatrixElaboratorDialogBase)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 0, 381, 271))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 361, 31))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.inputDEM = QtGui.QTextEdit(self.groupBox)
        self.inputDEM.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputDEM.setObjectName(_fromUtf8("inputDEM"))
        self.DEM = QtGui.QPushButton(self.groupBox)
        self.DEM.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.DEM.setObjectName(_fromUtf8("DEM"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 110, 361, 31))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.SoilImage = QtGui.QPushButton(self.groupBox_3)
        self.SoilImage.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.SoilImage.setObjectName(_fromUtf8("SoilImage"))
        self.inputSoilImage = QtGui.QTextEdit(self.groupBox_3)
        self.inputSoilImage.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputSoilImage.setObjectName(_fromUtf8("inputSoilImage"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 70, 361, 31))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.FieldImage = QtGui.QPushButton(self.groupBox_2)
        self.FieldImage.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.FieldImage.setObjectName(_fromUtf8("FieldImage"))
        self.inputFieldImage = QtGui.QTextEdit(self.groupBox_2)
        self.inputFieldImage.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputFieldImage.setObjectName(_fromUtf8("inputFieldImage"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 150, 361, 31))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.PrecipitationImage = QtGui.QPushButton(self.groupBox_4)
        self.PrecipitationImage.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.PrecipitationImage.setObjectName(_fromUtf8("PrecipitationImage"))
        self.inputPrecipitationImage = QtGui.QTextEdit(self.groupBox_4)
        self.inputPrecipitationImage.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputPrecipitationImage.setObjectName(_fromUtf8("inputPrecipitationImage"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 230, 361, 31))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.ManagementImage = QtGui.QPushButton(self.groupBox_6)
        self.ManagementImage.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.ManagementImage.setObjectName(_fromUtf8("ManagementImage"))
        self.inputManagementImage = QtGui.QTextEdit(self.groupBox_6)
        self.inputManagementImage.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputManagementImage.setObjectName(_fromUtf8("inputManagementImage"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 190, 361, 31))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.LandCover = QtGui.QPushButton(self.groupBox_5)
        self.LandCover.setGeometry(QtCore.QRect(310, 0, 51, 32))
        self.LandCover.setObjectName(_fromUtf8("LandCover"))
        self.inputLandCover = QtGui.QTextEdit(self.groupBox_5)
        self.inputLandCover.setGeometry(QtCore.QRect(140, 0, 171, 31))
        self.inputLandCover.setObjectName(_fromUtf8("inputLandCover"))
        self.groupBox_8 = QtGui.QGroupBox(MatrixElaboratorDialogBase)
        self.groupBox_8.setGeometry(QtCore.QRect(420, 0, 231, 271))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 121, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox.setGeometry(QtCore.QRect(160, 30, 62, 16))
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(160, 60, 62, 16))
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.checkBox = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox.setGeometry(QtCore.QRect(20, 240, 151, 20))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.ShorterBox = QtGui.QCheckBox(self.groupBox_8)
        self.ShorterBox.setGeometry(QtCore.QRect(110, 190, 71, 18))
        self.ShorterBox.setChecked(True)
        self.ShorterBox.setAutoExclusive(True)
        self.ShorterBox.setObjectName(_fromUtf8("ShorterBox"))
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(10, 200, 71, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.checkBox_3 = QtGui.QCheckBox(self.groupBox_8)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 90, 191, 18))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.label_10 = QtGui.QLabel(self.groupBox_8)
        self.label_10.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(160, 130, 62, 16))
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(10, 160, 121, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_8)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(160, 160, 62, 16))
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.LongestBox = QtGui.QCheckBox(self.groupBox_8)
        self.LongestBox.setGeometry(QtCore.QRect(110, 210, 85, 18))
        self.LongestBox.setAutoExclusive(True)
        self.LongestBox.setObjectName(_fromUtf8("LongestBox"))
        self.groupBox_9 = QtGui.QGroupBox(MatrixElaboratorDialogBase)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 270, 631, 51))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.RasterPath = QtGui.QTextEdit(self.groupBox_9)
        self.RasterPath.setGeometry(QtCore.QRect(120, 20, 461, 31))
        self.RasterPath.setObjectName(_fromUtf8("RasterPath"))
        self.RasterPathButton = QtGui.QPushButton(self.groupBox_9)
        self.RasterPathButton.setGeometry(QtCore.QRect(580, 20, 51, 32))
        self.RasterPathButton.setObjectName(_fromUtf8("RasterPathButton"))
        self.pushButton = QtGui.QPushButton(MatrixElaboratorDialogBase)
        self.pushButton.setGeometry(QtCore.QRect(20, 330, 110, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(MatrixElaboratorDialogBase)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 330, 110, 32))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))

        self.retranslateUi(MatrixElaboratorDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")),
                               MatrixElaboratorDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")),
                               MatrixElaboratorDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MatrixElaboratorDialogBase)

    def retranslateUi(self, MatrixElaboratorDialogBase):
        MatrixElaboratorDialogBase.setWindowTitle(
            _translate("MatrixElaboratorDialogBase", "Earh Matrix Elaborator", None))
        self.groupBox_7.setTitle(_translate("MatrixElaboratorDialogBase", "Input Raster", None))
        self.label.setText(_translate("MatrixElaboratorDialogBase", "DEM Image", None))
        self.DEM.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_3.setText(_translate("MatrixElaboratorDialogBase", "Soil Image", None))
        self.SoilImage.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_2.setText(_translate("MatrixElaboratorDialogBase", "Field image", None))
        self.FieldImage.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_4.setText(_translate("MatrixElaboratorDialogBase", "Precipitation Image", None))
        self.PrecipitationImage.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_6.setText(_translate("MatrixElaboratorDialogBase", "Management image", None))
        self.ManagementImage.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_5.setText(_translate("MatrixElaboratorDialogBase", "Land-cover image", None))
        self.LandCover.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.groupBox_8.setTitle(_translate("MatrixElaboratorDialogBase", "Control Specification", None))
        self.label_7.setText(_translate("MatrixElaboratorDialogBase", "Aspect Threshold", None))
        self.label_8.setText(_translate("MatrixElaboratorDialogBase", "Maximum Slope Lenght", None))
        self.checkBox.setText(_translate("MatrixElaboratorDialogBase", "All in Metric System", None))
        self.ShorterBox.setText(_translate("MatrixElaboratorDialogBase", "shorter", None))
        self.label_9.setText(_translate("MatrixElaboratorDialogBase", "Rounded to", None))
        self.checkBox_3.setText(_translate("MatrixElaboratorDialogBase", "Average soil factory patcher", None))
        self.label_10.setText(_translate("MatrixElaboratorDialogBase", "Aspect_threshold", None))
        self.label_11.setText(_translate("MatrixElaboratorDialogBase", "Smallest patch size", None))
        self.LongestBox.setText(_translate("MatrixElaboratorDialogBase", "longer", None))
        self.groupBox_9.setTitle(_translate("MatrixElaboratorDialogBase", "Output Raster", None))
        self.label_12.setText(_translate("MatrixElaboratorDialogBase", "Raster Path", None))
        self.RasterPathButton.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.pushButton.setText(_translate("MatrixElaboratorDialogBase", "Load Config", None))
        self.pushButton_2.setText(_translate("MatrixElaboratorDialogBase", "Save Config", None))

