# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RUSLECalculator_dialog_base.ui'
#
# Created: Mon Nov 16 10:58:34 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MatrixElaboratorDialogBase(object):
    def setupUi(self, MatrixElaboratorDialogBase):
        MatrixElaboratorDialogBase.setObjectName(_fromUtf8("MatrixElaboratorDialogBase"))
        MatrixElaboratorDialogBase.resize(739, 441)
        self.button_box = QtGui.QDialogButtonBox(MatrixElaboratorDialogBase)
        self.button_box.setGeometry(QtCore.QRect(550, 390, 171, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.groupBox_7 = QtGui.QGroupBox(MatrixElaboratorDialogBase)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 10, 641, 271))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 30, 631, 31))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_3 = QtGui.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.buttonR = QtGui.QPushButton(self.groupBox_3)
        self.buttonR.setGeometry(QtCore.QRect(580, -9, 51, 51))
        self.buttonR.setObjectName(_fromUtf8("buttonR"))
        self.inputR = QtGui.QTextEdit(self.groupBox_3)
        self.inputR.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputR.setObjectName(_fromUtf8("inputR"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 70, 631, 31))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.buttonK = QtGui.QPushButton(self.groupBox_4)
        self.buttonK.setGeometry(QtCore.QRect(580, -9, 51, 51))
        self.buttonK.setObjectName(_fromUtf8("buttonK"))
        self.inputK = QtGui.QTextEdit(self.groupBox_4)
        self.inputK.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputK.setObjectName(_fromUtf8("inputK"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 150, 631, 31))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_6)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.buttonC = QtGui.QPushButton(self.groupBox_6)
        self.buttonC.setGeometry(QtCore.QRect(580, -9, 51, 51))
        self.buttonC.setObjectName(_fromUtf8("buttonC"))
        self.inputC = QtGui.QTextEdit(self.groupBox_6)
        self.inputC.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputC.setObjectName(_fromUtf8("inputC"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 110, 631, 31))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.buttonLS = QtGui.QPushButton(self.groupBox_5)
        self.buttonLS.setGeometry(QtCore.QRect(580, -9, 51, 51))
        self.buttonLS.setObjectName(_fromUtf8("buttonLS"))
        self.inputLS = QtGui.QTextEdit(self.groupBox_5)
        self.inputLS.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputLS.setObjectName(_fromUtf8("inputLS"))
        self.groupBox = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox.setGeometry(QtCore.QRect(0, 230, 631, 31))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.inputDEM = QtGui.QTextEdit(self.groupBox)
        self.inputDEM.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputDEM.setObjectName(_fromUtf8("inputDEM"))
        self.buttonDem = QtGui.QPushButton(self.groupBox)
        self.buttonDem.setGeometry(QtCore.QRect(580, -10, 51, 51))
        self.buttonDem.setObjectName(_fromUtf8("buttonDem"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 190, 631, 31))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.inputP = QtGui.QTextEdit(self.groupBox_2)
        self.inputP.setGeometry(QtCore.QRect(130, 0, 451, 31))
        self.inputP.setObjectName(_fromUtf8("inputP"))
        self.buttonP = QtGui.QPushButton(self.groupBox_2)
        self.buttonP.setGeometry(QtCore.QRect(580, -10, 51, 51))
        self.buttonP.setObjectName(_fromUtf8("buttonP"))
        self.groupBox_9 = QtGui.QGroupBox(MatrixElaboratorDialogBase)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 290, 631, 71))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_12 = QtGui.QLabel(self.groupBox_9)
        self.label_12.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.RasterPath = QtGui.QTextEdit(self.groupBox_9)
        self.RasterPath.setGeometry(QtCore.QRect(130, 30, 451, 31))
        self.RasterPath.setObjectName(_fromUtf8("RasterPath"))
        self.RasterPathButton = QtGui.QPushButton(self.groupBox_9)
        self.RasterPathButton.setGeometry(QtCore.QRect(580, 30, 51, 32))
        self.RasterPathButton.setObjectName(_fromUtf8("RasterPathButton"))
        self.years_input = QtGui.QSpinBox(MatrixElaboratorDialogBase)
        self.years_input.setGeometry(QtCore.QRect(140, 380, 111, 31))
        self.years_input.setMinimum(1)
        self.years_input.setObjectName(_fromUtf8("years_input"))
        self.years_label = QtGui.QLabel(MatrixElaboratorDialogBase)
        self.years_label.setGeometry(QtCore.QRect(20, 390, 101, 17))
        self.years_label.setObjectName(_fromUtf8("years_label"))
        self.label_7 = QtGui.QLabel(MatrixElaboratorDialogBase)
        self.label_7.setGeometry(QtCore.QRect(640, 10, 101, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.checkerR = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerR.setGeometry(QtCore.QRect(680, 40, 16, 31))
        self.checkerR.setObjectName(_fromUtf8("checkerR"))
        self.checkerK = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerK.setGeometry(QtCore.QRect(680, 80, 16, 31))
        self.checkerK.setObjectName(_fromUtf8("checkerK"))
        self.checkerLS = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerLS.setGeometry(QtCore.QRect(680, 120, 16, 31))
        self.checkerLS.setObjectName(_fromUtf8("checkerLS"))
        self.checkerC = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerC.setGeometry(QtCore.QRect(680, 160, 16, 31))
        self.checkerC.setObjectName(_fromUtf8("checkerC"))
        self.checkerDEM = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerDEM.setGeometry(QtCore.QRect(680, 240, 16, 31))
        self.checkerDEM.setObjectName(_fromUtf8("checkerDEM"))
        self.checkerP = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerP.setGeometry(QtCore.QRect(680, 200, 16, 31))
        self.checkerP.setObjectName(_fromUtf8("checkerP"))
        self.checkerOutput = QtGui.QCheckBox(MatrixElaboratorDialogBase)
        self.checkerOutput.setGeometry(QtCore.QRect(680, 320, 16, 31))
        self.checkerOutput.setObjectName(_fromUtf8("checkerOutput"))

        self.retranslateUi(MatrixElaboratorDialogBase)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("accepted()")), MatrixElaboratorDialogBase.accept)
        QtCore.QObject.connect(self.button_box, QtCore.SIGNAL(_fromUtf8("rejected()")), MatrixElaboratorDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(MatrixElaboratorDialogBase)

    def retranslateUi(self, MatrixElaboratorDialogBase):
        MatrixElaboratorDialogBase.setWindowTitle(_translate("MatrixElaboratorDialogBase", "Earh Matrix Elaborator", None))
        self.groupBox_7.setTitle(_translate("MatrixElaboratorDialogBase", "Input Raster", None))
        self.label_3.setText(_translate("MatrixElaboratorDialogBase", "Erosion of rainfall (R)", None))
        self.buttonR.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_4.setText(_translate("MatrixElaboratorDialogBase", "Erosivity soil (K)", None))
        self.buttonK.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_6.setText(_translate("MatrixElaboratorDialogBase", "Vegetation Soil (C)", None))
        self.buttonC.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_5.setText(_translate("MatrixElaboratorDialogBase", "Slope lenght (LS)", None))
        self.buttonLS.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label.setText(_translate("MatrixElaboratorDialogBase", "DEM", None))
        self.buttonDem.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.label_2.setText(_translate("MatrixElaboratorDialogBase", "P Factor (P)", None))
        self.buttonP.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.groupBox_9.setTitle(_translate("MatrixElaboratorDialogBase", "Output Raster", None))
        self.label_12.setText(_translate("MatrixElaboratorDialogBase", "Raster Path", None))
        self.RasterPathButton.setText(_translate("MatrixElaboratorDialogBase", "...", None))
        self.years_label.setText(_translate("MatrixElaboratorDialogBase", "Number of years", None))
        self.label_7.setText(_translate("MatrixElaboratorDialogBase", "Multiple input", None))
        self.checkerR.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerK.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerLS.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerC.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerDEM.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerP.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))
        self.checkerOutput.setText(_translate("MatrixElaboratorDialogBase", "CheckBox", None))

